categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🗎 Documentation'
    label: 'documentation'
exclude-contributors:
  - 'renovate'
exclude-labels:
  - 'dependencies'
template: |
  ## What’s Changed

  $CHANGES
