language: java

cache:
  directories:
  - $HOME/.m2

jdk:
  - openjdk8
  - openjdk11

os:
  - linux

install:
  - mvn -B -V -DskipTests=true -Dmaven.javadoc.skip=true install

script: mvn -B -V -Pcoverage verify coveralls:report
